### ISSUE TITLE
waiting for write JWTs to expire

### ISSUE THREAD

**Issue by appinteractive** [PierreAndreis/do-registry-prune-tags#33]
Hey @PierreAndreis Thanks for that neat little action! 

I encountered an issue where the garbage collection locks my regestry after running your action with the status: `waiting for write JWTs to expire`. I'm using v1.0.1.

<img width="951" alt="grafik" src="https://user-images.githubusercontent.com/432828/124099746-20fa7d00-da5e-11eb-95f6-d64f4d7e7f0d.png">

**Comment by appinteractive** [comment]
Seems that the status for the JWTs comes from the registry login before building. Thats okay but after that it did not clean up still: 
<img width="1002" alt="grafik" src="https://user-images.githubusercontent.com/432828/124101385-97e44580-da5f-11eb-9377-cf4255b2dc7f.png">

**Comment by PierreAndreis** [comment]
Hey @appinteractive, thanks for writing our first issue! 🥳 

Garbage collection does not remove the images but cleans up all the artifacts not associated with any manifest anymore and still occupy space.

> I encountered an issue where the garbage collection locks my registry after running your action with the status: waiting for write JWTs to expire.

[DigitalOcean specifies in their docs](https://docs.digitalocean.com/products/container-registry/how-to/clean-up-container-registry/#considerations) that it needs to wait for all the tokens that have to write permission to expire first before running it.
Tokens with write permissions are issued mostly right before you push a new image to a container registry. If you are using their cli, the command would be `doctl registry docker-config --read-write`, and they last 10 minutes. 

> Also, did it not remove anything at all, even it had shown a lot of prune ones in the output.

Regardless of GC, if the token given to the action has permission to write, it should have pruned the images tags listed on the table from each of your repositories, and you should be able to confirm that by either using their CLI or their portal. 
Can you ensure that the token you have given has permission to write and tags are still there?

**Comment by appinteractive** [comment]
Hey @PierreAndreis I resolved it by running it as a crone job with GitHub actions. 

```yaml

name: Clean Docker Registry

on:
  workflow_dispatch:

  schedule:
    # run daily on 2 AM
    - cron: "0 2 * * *"

jobs:
  clean-docker-regestry:
    name: Clean Docker Registry

    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DO Container Registry
        run: doctl registry login --expiry-seconds 30

      - name: DigitalOcean Registry Prune
        uses: PierreAndreis/do-registry-prune-tags@1.0.1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

```
