### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by Cretezy** [PierreAndreis/do-registry-prune-tags#49]
When running this action, I see no output

![image](https://user-images.githubusercontent.com/2672503/126522081-283d53fc-2d04-4c20-a2be-8434abe13a93.png)

Here's my workflow file:

```yaml
name: Prune

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  prune:
    name: Prune
    runs-on: ubuntu-latest
    steps:
      - name: DigitalOcean Registry Prune
        uses: PierreAndreis/do-registry-prune-tags@0.0.1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
```
